// js/resources.js

export const RESOURCES = {
    id: {
        welcome_msg: "Selamat Datang di Aplikasi Finansial Pro",
        msg_empty_trans: "Belum ada transaksi tercatat",
        msg_empty_bill: "Belum ada tagihan rutin",
        msg_empty_goal: "Belum ada target tabungan",
        msg_empty_loan: "Belum ada data pinjaman",
        
        wallet_cash: "Tunai",
        wallet_bank: "Bank/ATM",
        wallet_ewallet: "E-Wallet",
        
        nav_home: "Beranda",
        nav_budget: "BudgetKu",
        nav_tools: "Tools",
        nav_loans: "Pinjaman",
        nav_settings: "Setelan",
        nav_calc: "Kalkulator",
        
        total_net_worth: "Total Kekayaan Bersih",
        lbl_in: "Masuk",
        lbl_out: "Keluar",
        total_receivable: "Total Piutang",
        total_debt: "Total Hutang",
        em_fund_title: "Dana Darurat",
        em_check_status: "Cek Status Aman",
        em_not_set: "Belum diset",
        cashflow_title: "Arus Kas Bulan Ini",
        
        lbl_confirm_title: "Konfirmasi",
        btn_cancel: "Batal",
        btn_yes: "Ya, Lanjutkan",
        
        tab_bills: "Tagihan",
        add_bill_title: "Tambah Tagihan Rutin",
        ph_bill_name: "Nama (cth: WiFi, Listrik)",
        lbl_due_date: "Jatuh Tempo Tanggal:",
        bill_list_title: "Tagihan Bulan Ini",
        btn_pay_bill: "Bayar Sekarang",
        msg_bill_paid: "Tagihan berhasil dibayar!",
        status_paid: "LUNAS",
        status_unpaid: "BELUM",
        status_overdue: "TELAT",
        lbl_search_budget: "Cari Transaksi..",
        lbl_search_loan: "Cari Pinjaman..",
        
        tab_trans: "Transaksi",
        tab_plan: "Planning & Target",
        recent_history: "Riwayat Terakhir",
        add_new_goal: "Tambah Target Baru",
        ph_goal_name: "Nama Target (misal: Beli iPhone)",
        ph_goal_amount: "Target Nominal (Rp)",
        btn_save: "Simpan",
        goal_hint: "Klik pada kartu target untuk menambah tabungan.",
        
        lbl_interest_rate: "Bunga (%/bln)",
        lbl_tenor_month: "Tenor (Bulan)",
        lbl_installment: "Cicilan/bln",
        
        sts_due_today: "JATUH TEMPO HARI INI!",
        sts_due_in: "Jatuh Tempo: H-",
        sts_late: "TELAT",
        sts_day: "Hari",

        tab_active: "Aktif",
        tab_history: "Riwayat Lunas",
        lbl_pay_history: "Riwayat Pembayaran",
        ph_search_name: "Cari nama...",
        archive_paid: "Arsip Lunas",
        
        tip_delete_pay: "Hapus Pembayaran ini",
        confirm_del_pay: "Hapus catatan pembayaran ini? Saldo hutang akan kembali bertambah.",
        msg_pay_deleted: "Pembayaran dibatalkan/dihapus",
                
        collected: "Terkumpul",
        your_target: "Target Kamu",
        month: "Bulan",
        btn_add_savings: "Tambah Tabungan",
        risk_profile_title: "Atur Profil Risiko",
        risk_profile_desc: "Aplikasi akan menghitung target ideal berdasarkan profil risiko hidup Anda secara otomatis.",
        lbl_expense: "Pengeluaran Bulanan (Rata-rata)",
        ph_expense: "Contoh: 3.000.000",
        lbl_job_status: "Status Pekerjaan",
        opt_stable: "Karyawan Tetap / PNS (Stabil)",
        opt_freelance: "Freelance / Bisnis (Fluktuatif)",
        lbl_dependents: "Jumlah Tanggungan",
        opt_single: "Sendiri (Single)",
        opt_family_small: "1-2 Orang (Keluarga Kecil)",
        opt_family_large: "3+ Orang (Keluarga Besar)",
        btn_recalc: "Hitung Ulang Target",

        lbl_principal: "Modal Awal/Modal Saat Ini (Rp)",
        lbl_inv_method: "Pilih Metode Investasi",
        opt_lump: "Tidak Ada (Lump Sum)",
        opt_daily: "Nabung Harian",
        opt_weekly: "Nabung Mingguan",
        opt_monthly: "Nabung Bulanan",
        opt_yearly: "Nabung Tahunan",
        lbl_routine_amount: "Nominal Rutin (Rp)",
        lbl_duration: "Durasi (Thn)",
        btn_calc_sim: "Hitung Simulasi",
        est_total: "Estimasi Total Akhir:",
        lbl_capital: "Modal Disetor:",
        lbl_interest: "Bunga/Cuan:",

        pref_title: "Preferensi",
        lbl_lang: "Bahasa",
        lbl_select_lang: "Pilih Bahasa",
        btn_choose_file: "Pilih File",
        btn_download: "Simpan",
        danger_zone_title: "Hapus Data !",
        danger_zone_desc: "Data yang dihapus tidak bisa dipulihkan.",
        btn_reset_data: "Reset Semua Data",

        modal_trans_title: "Catat Keuangan",
        lbl_expense_type: "Pengeluaran",
        lbl_income_type: "Pemasukan",
        ph_desc: "Keterangan (cth: Makan Siang)",
        
        modal_loan_title: "Catat Pinjaman",
        lbl_trans_type: "Tipe Transaksi",
        opt_lend: "Saya Meminjamkan (Piutang)",
        opt_borrow: "Saya Berhutang (Hutang)",
        lbl_person_name: "Nama Orang/Pihak Kedua",
        lbl_principal_loan: "Pokok Pinjaman",
        lbl_trans_date: "Tanggal Transaksi",
        lbl_installment: "Cicilan/bln:",
        lbl_total_final: "Total Akhir:",
        
        modal_detail_title: "Rincian Transaksi",
        modal_save_title: "Tabung Dana",
        ask_amount_add: "Berapa nominal yang ingin kamu tambahkan?",
        lbl_deposit_amount: "Nominal Setor (Rp)",
        
        em_modal_desc: "Amankan masa depanmu dengan menabung hari ini.",
        em_tip: "Sisihkan uang receh atau sisa belanja harian Anda di sini agar tidak terasa berat.",
        btn_save_savings: "Simpan Tabungan",

        word_receivable: "PIUTANG",
        word_debt: "HUTANG",
        word_remaining: "Sisa",
        ph_amount: "Nominal",
        btn_delete_data: "Hapus Data Ini",
        
        fab_trans: "Catat Transaksi",
        fab_loan: "Catat Hutang/Piutang",
        fab_emergency: "Tabung Dana Darurat",

        security_title: "Keamanan Aplikasi",
        enable_pin: "Aktifkan PIN",
        disable_pin: "Nonaktifkan PIN",
        enter_pin: "Masukkan PIN Keamanan",
        setup_pin: "Buat PIN Baru (4 Angka)",
        pin_wrong: "PIN Salah!",
        pin_set: "PIN Keamanan Diaktifkan!",
        pin_unset: "PIN Dinonaktifkan",
        confirm_disable_pin: "Matikan keamanan PIN?",

        msg_complete_data: "Mohon lengkapi data",
        msg_trans_saved: "Transaksi berhasil dicatat",
        msg_invalid_goal: "Data target tidak valid",
        msg_goal_created: "Target baru dibuat",
        msg_invalid_amount: "Nominal tidak valid",
        msg_success_add: "Berhasil menambah",
        msg_loan_saved: "Data pinjaman tersimpan",
        msg_paid: "LUNAS",
        msg_payment_recorded: "Pembayaran dicatat",
        msg_fill_year: "Durasi tahun harus diisi",
        msg_confirm_del: "Yakin hapus item ini?",
        msg_confirm_reset: "PERINGATAN: Semua data akan hilang permanen! Lanjutkan?",
        msg_prof_saved: "Profil tersimpan! Target Anda:",
        
        word_bill: "Total Tagihan",
        msg_loading: "Memuat data...",
        login_desc: "Kelola keuanganmu dengan aman, tersinkronisasi di awan.",
        btn_login_google: "Masuk dengan Google",
        
        lbl_trend_chart: "Tren Pengeluaran (6 Bulan)",
        lbl_calc_title: "Bunga Majemuk (Compound)",
        lbl_return_rate: "Return (%/thn)",
        
        lbl_asset_growth: "Pertumbuhan Aset",
        col_year: "Thn",
        col_total_modal: "Total Modal",
        col_final_bal: "Saldo Akhir",
        
        lbl_backup_data: "Backup Data (JSON)",
        lbl_restore_data: "Restore Data (JSON)",
        lbl_google_account: "Akun Google",
        btn_logout: "Keluar / Logout",
        lbl_about_privacy: "Tentang & Privasi",
        btn_read: "Baca",
        lbl_contact_dev: "Kontak Developer",
        btn_email: "Email",
        
        // Label Modal Konfirmasi (Default HTML)
        msg_confirm_default: "Apakah anda yakin?",
        btn_yes_delete: "Ya, Hapus",
        word_pay: "Bayar"
    },
    en: {
        welcome_msg: "Welcome to Finansial Pro App",
        msg_empty_trans: "No transactions recorded yet",
        msg_empty_bill: "No recurring bills yet",
        msg_empty_goal: "No saving goals yet",
        msg_empty_loan: "No loan records yet",
        
        wallet_cash: "Cash",
        wallet_bank: "Bank/ATM",
        wallet_ewallet: "E-Wallet",
        
        nav_home: "Home",
        nav_budget: "Budget",
        nav_tools: "Tools",
        nav_loans: "Loans",
        nav_settings: "Settings",
        nav_calc: "Calculator",
        
        total_net_worth: "Total Net Worth",
        lbl_in: "Income",
        lbl_out: "Expense",
        total_receivable: "Total Receivable",
        total_debt: "Total Debt",
        em_fund_title: "Emergency Fund",
        em_check_status: "Check Status",
        em_not_set: "Not set",
        cashflow_title: "Cashflow This Month",
        
        lbl_confirm_title: "Confirmation",
        btn_cancel: "Cancel",
        btn_yes: "Yes, Proceed",
        
        tab_bills: "Bills",
        add_bill_title: "Add Recurring Bill",
        ph_bill_name: "Name (e.g. WiFi, Power)",
        lbl_due_date: "Due Date:",
        bill_list_title: "Bills This Month",
        btn_pay_bill: "Pay Now",
        msg_bill_paid: "Bill paid successfully!",
        status_paid: "PAID",
        status_unpaid: "UNPAID",
        status_overdue: "LATE",
        lbl_search_budget: "Search Transactions..",
        lbl_search_loan: "Search Loans..",
        
        tab_trans: "Transactions",
        tab_plan: "Planning & Goals",
        recent_history: "Recent History",
        add_new_goal: "Add New Goal",
        ph_goal_name: "Goal Name (e.g., Buy iPhone)",
        ph_goal_amount: "Target Amount (Rp)",
        btn_save: "Save",
        goal_hint: "Click on a goal card to add savings.",

        lbl_interest_rate: "Interest Rate (%/mo)",
        lbl_tenor_month: "Duration (Months)",
        lbl_installment: "Installment/mo",
        
        sts_due_today: "DUE TODAY!",
        sts_due_in: "Due in: D-",
        sts_late: "OVERDUE",
        sts_day: "Days",
        
        tab_active: "Active",
        tab_history: "Paid History",
        lbl_pay_history: "Payment History",
        ph_search_name: "Search name...",
        archive_paid: "Paid Archive",                

        tip_delete_pay: "Delete this payment",
        confirm_del_pay: "Delete this payment record? Debt balance will increase.",
        msg_pay_deleted: "Payment cancelled/deleted",
        
        collected: "Collected",
        your_target: "Your Target",
        month: "Months",
        btn_add_savings: "Add Savings",
        risk_profile_title: "Risk Profile",
        risk_profile_desc: "App will calculate ideal target based on your life risk profile automatically.",
        lbl_expense: "Monthly Expense (Average)",
        ph_expense: "Ex: 3.000.000",
        lbl_job_status: "Job Status",
        opt_stable: "Permanent Employee / Gov (Stable)",
        opt_freelance: "Freelance / Business (Fluctuating)",
        lbl_dependents: "Dependents",
        opt_single: "Single (Alone)",
        opt_family_small: "1-2 People (Small Family)",
        opt_family_large: "3+ People (Large Family)",
        btn_recalc: "Recalculate Target",

        lbl_principal: "Initial Capital (Rp)",
        lbl_inv_method: "Select Invest Method",
        opt_lump: "None (Lump Sum)",
        opt_daily: "Daily Savings",
        opt_weekly: "Weekly Savings",
        opt_monthly: "Monthly Savings",
        opt_yearly: "Yearly Savings",
        lbl_routine_amount: "Routine Amount (Rp)",
        lbl_duration: "Duration (Yrs)",
        btn_calc_sim: "Calculate Simulation",
        est_total: "Estimated Total:",
        lbl_capital: "Capital Invested:",
        lbl_interest: "Interest/Profit:",

        pref_title: "Preferences",
        lbl_lang: "Language",
        lbl_select_lang: "Select Language",
        btn_choose_file: "Choose File",
        btn_download: "Download",
        danger_zone_title: "Delete Data !",
        danger_zone_desc: "Deleted data cannot be recovered.",
        btn_reset_data: "Reset All Data",

        modal_trans_title: "Record Finance",
        lbl_expense_type: "Expense",
        lbl_income_type: "Income",
        ph_desc: "Description (e.g., Lunch)",
        
        modal_loan_title: "Record Loan",
        lbl_trans_type: "Transaction Type",
        opt_lend: "I am Lending (Receivable)",
        opt_borrow: "I am Borrowing (Debt)",
        lbl_person_name: "Person Name",
        lbl_principal_loan: "Principal Loan",
        lbl_trans_date: "Transaction Date",
        lbl_installment: "Installment/mo:",
        lbl_total_final: "Final Total:",
        
        modal_detail_title: "Transaction Detail",
        modal_save_title: "Save Funds",
        ask_amount_add: "How much to add?",
        lbl_deposit_amount: "Deposit Amount (Rp)",
        
        em_modal_desc: "Secure your future by saving today.",
        em_tip: "Set aside loose change or daily shopping changes here so it doesn't feel heavy.",
        btn_save_savings: "Save Savings",
        
        word_receivable: "LENDING", 
        word_debt: "DEBT",
        word_remaining: "Remaining",
        ph_amount: "Amount",
        btn_delete_data: "Delete Data",

        fab_trans: "Record Transaction",
        fab_loan: "Record Loan",
        fab_emergency: "Add Emergency Fund",

        security_title: "App Security",
        enable_pin: "Enable PIN",
        disable_pin: "Disable PIN",
        enter_pin: "Enter Security PIN",
        setup_pin: "Create New PIN (4 Digits)",
        pin_wrong: "Wrong PIN!",
        pin_set: "Security PIN Enabled!",
        pin_unset: "PIN Disabled",
        confirm_disable_pin: "Disable PIN security?",

        msg_complete_data: "Please complete data",
        msg_trans_saved: "Transaction saved successfully",
        msg_invalid_goal: "Invalid goal data",
        msg_goal_created: "New goal created",
        msg_invalid_amount: "Invalid amount",
        msg_success_add: "Successfully added",
        msg_loan_saved: "Loan data saved",
        msg_paid: "PAID OFF",
        msg_payment_recorded: "Payment recorded",
        msg_fill_year: "Year duration is required",
        msg_confirm_del: "Are you sure to delete this item?",
        msg_confirm_reset: "WARNING: All data will be lost permanently! Continue?",
        msg_prof_saved: "Profile saved! Your Target:",

        word_bill: "Total Bill",
        msg_loading: "Loading data...",
        login_desc: "Manage your finances securely, synced in the cloud.",
        btn_login_google: "Sign in with Google",
        
        lbl_trend_chart: "Expense Trend (6 Months)",
        lbl_calc_title: "Compound Interest",
        lbl_return_rate: "Return (%/yr)",
        
        lbl_asset_growth: "Asset Growth",
        col_year: "Yr",
        col_total_modal: "Total Capital",
        col_final_bal: "Final Balance",
        
        lbl_backup_data: "Backup Data (JSON)",
        lbl_restore_data: "Restore Data (JSON)",
        lbl_google_account: "Google Account",
        btn_logout: "Logout",
        lbl_about_privacy: "About & Privacy",
        btn_read: "Read",
        lbl_contact_dev: "Contact Developer",
        btn_email: "Email",
        
        // Confirmation Modal Labels
        msg_confirm_default: "Are you sure?",
        btn_yes_delete: "Yes, Delete",
        word_pay: "Pay"
    }
};
